
[build]
target = "x86_64-preset.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]


[target.'cfg(target_os = "none")']
runner = "bootimage runner"
